### ISSUE TITLE
Engine

### ISSUE THREAD

**Issue by Emir2099** [LordMaddog/DarkSouls-Like_CombatSystem-UE5#2]
Hello! I am really thankful to you for putting this all together. The thing is I downloaded it and tried to open it in ue5.0 and 5.3 (I am unable to download 5.1 or 5.2 idk why it get stuck on 82% installation(. The thing is I am unable to load the playing map and most of the contents in DATA folder is missing too if I am not wrong. Can you please guide how to actually play this combat system. It will be really helpful. Thank you so much.

**Comment by LordMaddog** [comment]
It is made in 5.2 so 5.0 will not work. It may be possible for you to update it to 5.3 or higher though that might make bugs but I don't know for sure because I have not tried it yet my self.
Here is a link describing how to upgrade.
https://www.youtube.com/watch?v=MTf6r0PdJWI&ab_channel=MattAspland

**Comment by Emir2099** [comment]
Thank you so much for the assist! I will try to upgrade it to 5.3. In case if you ever succeed to make a functional version of the system in 5.3 please do let me know.

**Comment by LordMaddog** [comment]
I updated to 5.5
